Update README.md
catalyst/moodle-auth_userkey pull request #16
Opened 2017-07-03 14:31 UTC by simonmallet

"As usual" isn't good enough for first timers like me.

2017-07-03 23:40 UTC, dmitriim requested changes

2017-07-03 23:40 UTC, dmitriim commented on README.md
> +1. Install the plugin in (Admin > Plugins > Install plugins).
Someone like me never uses GUI for installing plugins :) 
Would be good in this case to have something like "Install the plugin using admin interface (Admin > Plugins > Install plugins) or command line"

2017-07-03 23:40 UTC, dmitriim commented on README.md
> +1. Implement logout webservice to be able to call it from external application.
Not sure what was changed here?

2017-07-04 12:01 UTC, simonmallet commented on README.md
> +1. Implement logout webservice to be able to call it from external application.
That part wasn't me. I don't know why it sees it as a change :/

2017-07-10 23:55 UTC, dmitriim commented on README.md
> +1. Implement logout webservice to be able to call it from external application.
Maybe an extra empty line?

2018-04-09 23:37 UTC, dmitriim commented
Will close this one off as there is no much progress from the requester.

2018-04-09 23:37 UTC, closed without merging